# Risk keywords with their associated scores
risk_keywords:
  "wheat": 5
  "flour": 4
  "sugar": 3
  "yeast": 3
  "oil": 2
  "delivery delays": 5
  "price increase": 4
  "inflation": 3
  "labor shortage": 5
  "strike": 4
  "natural disaster": 5
  "pandemic": 5
  "drought": 4
  "trade restriction": 5
  "economic crisis": 5
  "crop failure": 4
  "supply chain disruption": 5
  "fuel shortage": 4
  "transportation issues": 5
  "global warming": 4
  "climate change": 5
  "harvest failure": 4
  "tariffs": 4
  "food safety scandal": 5
  "geopolitical tension": 4
  "import bans": 4
  "logistics breakdown": 5
  "factory shutdown": 5
  "worker strike": 4
  "energy crisis": 5
  "power outage": 3
  "railroad strike": 4

# Critical ingredients specific to a bakery company
critical_ingredients:
  "Wheat Flour":
    keywords: ["wheat", "flour", "grain", "milling", "wheat flour"]
  "Sugar":
    keywords: ["sugar", "sweetener", "glucose", "fructose", "sucrose"]
  "Yeast":
    keywords: ["yeast", "baker's yeast", "fermentation", "leavening agent"]
  "Butter":
    keywords: ["butter", "margarine", "dairy", "butterfat"]
  "Eggs":
    keywords: ["egg", "eggs", "egg substitute", "egg whites", "egg yolk"]
  "Oil":
    keywords: ["oil", "vegetable oil", "canola oil", "olive oil", "sunflower oil"]
  "Salt":
    keywords: ["salt", "sodium", "sea salt", "table salt", "kosher salt"]
  "Baking Powder":
    keywords: ["baking powder", "raising agent", "leavening powder"]
  "Milk":
    keywords: ["milk", "dairy", "milk powder", "skim milk", "whole milk"]
  "Chocolate":
    keywords: ["chocolate", "cocoa", "dark chocolate", "milk chocolate", "chocolate chips"]
  "Banana":
    keywords: ["banana", "bananas", "banana puree"]
  "Walnuts":
    keywords: ["walnuts", "nut", "nuts", "walnut"]
  "Brown Sugar":
    keywords: ["brown sugar", "molasses", "light brown sugar", "dark brown sugar"]
  "Raisins":
    keywords: ["raisins", "dried grapes", "sultanas"]
  "Oats":
    keywords: ["oats", "oatmeal", "rolled oats", "instant oats"]
  "Peanut Butter":
    keywords: ["peanut butter", "peanuts", "nut butter"]
  "Cinnamon":
    keywords: ["cinnamon", "ground cinnamon", "cinnamon sticks"]
  "Water":
    keywords: ["water", "filtered water", "spring water"]
  "Baking Soda":
    keywords: ["baking soda", "sodium bicarbonate", "bicarbonate of soda"]
  "Vanilla":
    keywords: ["vanilla", "vanilla extract", "vanillin"]
  "Blueberry":
    keywords: ["blueberry", "blueberries", "fruit"]

# Negative keywords to help classify tone (indicating a disruption, risk, or problem)
negative_keywords:
  - "crisis"
  - "failure"
  - "disaster"
  - "strike"
  - "loss"
  - "shutdown"
  - "shortage"
  - "out of stock"
  - "delayed"
  - "supply chain issues"
  - "unavailability"
  - "scarcity"
  - "bankruptcy"
  - "inflation"
  - "famine"
  - "collapse"
  - "economic downturn"
  - "pandemic"
  - "lockdown"
  - "emergency"
  - "unrest"
  - "food security"
  - "trade embargo"
  - "tariff"
  - "wildfire"
  - "storm"
  - "flood"
  - "earthquake"
  - "drought"
  - "import ban"
  - "blockade"
  - "price volatility"

# Regional risks with potential impacts
regional_risks:
  "weather_patterns":
    description: "Severe weather changes such as extreme heat, storms, frost, or drought that could disrupt supply chains or crop yields."
    keywords: ["heatwave", "frost", "storm", "flood", "hurricane", "drought"]
  "economic_conditions":
    description: "Economic downturns and financial instability that affect production costs, logistics, or consumer demand."
    keywords: ["economic downturn", "recession", "bankruptcy", "default"]
  "trade_policies":
    description: "Changes in trade policies, tariffs, or restrictions that affect imports and exports."
    keywords: ["tariff", "trade embargo", "import restriction", "export ban", "quota"]
  "labor_issues":
    description: "Worker strikes, labor shortages, or other labor-related disruptions that impact production or distribution."
    keywords: ["strike", "labor shortage", "work stoppage", "unemployment", "union negotiations"]
  "health_crisis":
    description: "Health-related crises such as pandemics or outbreaks that affect workforce availability and supply chains."
    keywords: ["pandemic", "virus", "health crisis", "lockdown", "quarantine"]
  "geopolitical_risks":
    description: "Geopolitical tensions, conflicts, or sanctions that disrupt international supply chains."
    keywords: ["sanctions", "conflict", "trade war", "blockade"]

# Additional ingredient tracking section
ingredient_tracking:
  include_in_all_articles: true
  track_all_critical_ingredients: true
  track_additional_ingredients:
    - "blueberry"
    - "vanilla"
    - "peanut butter"
  custom_ingredient_keywords:
    blueberry: ["blueberry", "blueberries", "fruit"]
    vanilla: ["vanilla", "vanilla extract", "vanillin"]
    peanut_butter: ["peanut butter", "peanuts", "nut butter"]

# Predictive impact factors
predictive_impact_factors:
  delays:
    description: "Expected production or transportation delays caused by supply chain issues."
    thresholds:
      low: 1
      medium: 3
      high: 5
