//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChainVisionDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int Id { get; set; }
        public string ArticleId { get; set; }
        public string Title { get; set; }
        public string DisplayText { get; set; }
        public string Description { get; set; }
        public Nullable<byte> SeverityRatingId { get; set; }
        public System.DateTime PublishedDateUTC { get; set; }
        public string Country { get; set; }
        public string ArticleUrl { get; set; }
    }
}
